service: my-serverless-mongodb

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-3
  stage: staging
  environment:
      MONGODB_URL: ${ssm:/raise-free-staging-db}
      MONGODB_DB_NAME: staging
      MONGODB_COLLECTION_NAME: metadata

plugins:
  - serverless-offline

functions:
  find:
    handler: handler.findDocuments
    events:
      - http:
          path: /find
          method: "post"
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
  create:
    handler: handler.createDocument
    events:
      - http:
          path: /create
          method: "post"
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
    
  update:
    handler: handler.updateDocument
    events:
      - http:
          path: /update
          method: "post"
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
